[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=80", "setuptools-scm>=8" ]

[project]
name = "smirnoff-plugins"
description = "Custom parameter handlers for extending SMIRNOFF force fields."
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "MIT" }
authors = [ { name = "Simon Boothroyd", email = "simon.boothroyd@colorado.edu" } ]
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = [ "version" ]
entry-points."openff.interchange.plugins.collections".DoubleExponentialCollection = "smirnoff_plugins.collections.nonbonded:SMIRNOFFDoubleExponentialCollection"
entry-points."openff.interchange.plugins.collections".SMIRNOFFAxilrodTellerCollection = "smirnoff_plugins.collections.nonbonded:SMIRNOFFAxilrodTellerCollection"
entry-points."openff.interchange.plugins.collections".SMIRNOFFDampedBuckingham68Collection = "smirnoff_plugins.collections.nonbonded:SMIRNOFFDampedBuckingham68Collection"
entry-points."openff.interchange.plugins.collections".SMIRNOFFDampedExp6810Collection = "smirnoff_plugins.collections.nonbonded:SMIRNOFFDampedExp6810Collection"
entry-points."openff.interchange.plugins.collections".SMIRNOFFDoubleExponentialVirtualSiteCollection = "smirnoff_plugins.collections.vsites:SMIRNOFFDoubleExponentialVirtualSiteCollection"
entry-points."openff.interchange.plugins.collections".SMIRNOFFMultipoleCollection = "smirnoff_plugins.collections.nonbonded:SMIRNOFFMultipoleCollection"
entry-points."openff.interchange.plugins.collections".SMIRNOFFUreyBradleyCollection = "smirnoff_plugins.collections.valence:SMIRNOFFUreyBradleyCollection"
entry-points."openff.toolkit.plugins.handlers".AxilrodTellerHandler = "smirnoff_plugins.handlers.nonbonded:AxilrodTellerHandler"
entry-points."openff.toolkit.plugins.handlers".DampedBuckingham68Handler = "smirnoff_plugins.handlers.nonbonded:DampedBuckingham68Handler"
entry-points."openff.toolkit.plugins.handlers".DampedExp6810Handler = "smirnoff_plugins.handlers.nonbonded:DampedExp6810Handler"
entry-points."openff.toolkit.plugins.handlers".DoubleExponentialHandler = "smirnoff_plugins.handlers.nonbonded:DoubleExponentialHandler"
entry-points."openff.toolkit.plugins.handlers".DoubleExponentialVirtualSiteHandler = "smirnoff_plugins.handlers.vsites:DoubleExponentialVirtualSiteHandler"
entry-points."openff.toolkit.plugins.handlers".MultipoleHandler = "smirnoff_plugins.handlers.nonbonded:MultipoleHandler"
entry-points."openff.toolkit.plugins.handlers".UreyBradleyHandler = "smirnoff_plugins.handlers.valence:UreyBradleyHandler"

[tool.setuptools]
include-package-data = true
packages.find.where = [ "." ]

[tool.setuptools_scm]
fallback_version = "0.0.0"

[tool.ruff]
line-length = 119
extend-include = [ "**/*.md", "README.md" ]
preview = true
lint.select = [ "E", "F", "I", "NPY", "RUF", "UP", "W" ]

[tool.mypy]
plugins = [ "pydantic.mypy" ]
warn_unused_configs = true
warn_unused_ignores = true
warn_incomplete_stub = true
show_error_codes = true

[[tool.mypy.overrides]]
module = [
  "openff.toolkit.*",
  "openff.units",
  "openff.units.openmm",
  "openmm",
  "openmm.app",
  "openmm.unit",
]
ignore_missing_imports = true

[tool.coverage]
run.omit = [
  "*/_tests/*",
  "*/data/*",
  "smirnoff_plugins/_version.py",
]
report.exclude_lines = [
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
  "pragma: no cover",
  "raise NotImplementedError",
]

[roolf.ruff.format]
include = [ "*.py", "*.pyi", "*.md", "**/*.py", "**/*.pyi", "**/*.md" ]
docstring-code-format = true
