name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  test:

    name: Test on ${{ matrix.os }}, Python ${{ matrix.environment }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        environment:
          - py312
          - py313

    steps:
    - uses: actions/checkout@v6.0.2

    - name: Set up virtual environment
      uses: prefix-dev/setup-pixi@v0.9.6
      with:
        pixi-version: v0.62.2
        environments: ${{ matrix.environment }}
        frozen: true

    - name: Run Tests
      run: pixi run -e ${{ matrix.environment }} run_tests

    - name: Run Example
      run: pixi run -e ${{ matrix.environment }} run_examples

    - name: Run mypy
      run: pixi run -e ${{ matrix.environment }} run_mypy

    - name: CodeCov
      uses: codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.os }}-py${{ matrix.environment }}
